POST  http://localhost:5000/login
Content-Type: application/json

{
    "email" : "mahadi@gmail.com",
    "password" : "hiya21"

}

###
POST  http://127.0.0.1:5000/signup
Content-Type: application/json

{
    "email" : "jhonitay@gmail.com",
    "password" : "jhonojhon",
    "username" : "jhonitay"


}